version: "3"
services:
  eurekaservice:
    build: ./EurekaService
    ports:
        - "8761:8761"
  zuulservice:
    build: ./ZuulService
    ports:
        - "8081:8081"
  addressrepositoryservice:
    build: ./AddressRepositoryService
  assessmentrepositoryservice:
    build: ./AssessmentRepositoryService
  batchrepositoryservice:
    build: ./BatchRepositoryService
  categoryrepositoryservice:
    build: ./CategoryRepositoryService
  configservice:
    build: ./ConfigService
    ports:
        - "8888:8888"
  graderepositoryservice:
    build: ./GradeRepositoryService
  noterepositoryservice:
    build: ./NoteRepositoryService
  pdfservice:
    build: ./PDFService
  panelfeedbackrepositoryservice:
    build: ./PanelFeedbackRepositoryService
  panelrepositoryservice:
    build: ./PanelRepositoryService
  traineerepositoryservice:
    build: ./TraineeRepositoryService
  trainerrepositoryservice:
    build: ./TrainerRepositoryService
  
